/**
 * Created by UserX on 10/25/2017.
 */


const MESSAGE_PREFIX = '1a3dace9cc';
const BUTTONS_BACKGROUND_COLOR = "#7D539F";
const BUTTONS_TEXT_COLOR = "#FFFFFF";

module.exports ={

  MESSAGE_PREFIX:MESSAGE_PREFIX,
  BUTTONS_BACKGROUND_COLOR:BUTTONS_BACKGROUND_COLOR,
  BUTTONS_TEXT_COLOR:BUTTONS_TEXT_COLOR,





}
